OPRIA_LEAD_EMAIL_TO = "jjusturi@gmail.com"

# SMTP
OPRIA_SMTP_HOST = "smtp.gmail.com"
OPRIA_SMTP_PORT = 587
OPRIA_SMTP_USER = "jjusturi@gmail.com"
OPRIA_SMTP_PASSWORD = "olou gsbq wsfb owxd"
OPRIA_SMTP_FROM = "jjusturi@gmail.com"
OPRIA_SMTP_USE_TLS = true
OPRIA_SMTP_USE_SSL = false
